### ISSUE TITLE
能提供解析效率的对比不

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/bingo2sql#1]
先关注大佬的新项目，666

比如说一样是go实现的https://github.com/GoDannyLai/binlog_rollback

**Comment by hanchuanchuan** [comment]
咱们两个可真是心有灵犀啊，我正在看你的项目是怎么集成binlog2sql的呢！！
![image](https://user-images.githubusercontent.com/18544383/75552760-f7000780-5a71-11ea-8ea6-fd6adec819f3.png)

**Comment by hanchuanchuan** [comment]
经过测试，和binlog_rollback项目的效率相近，后续会提供一些效率对比。

**Comment by hanchuanchuan** [comment]
[效率测试](https://github.com/hanchuanchuan/bingo2sql/blob/master/docs/test.md)
做了一些简单的测试，当前来说 binlog_rollback项目做的事情更多，所以效率稍低，实际上效率是差不多的(均使用的go-mysql依赖)。

**Comment by liuqian1990** [comment]
之前一直用binlog2sql,试用下大佬这个工具
