### ISSUE TITLE
--start-time有用么？

### ISSUE THREAD

**Issue by hope1234567hope** [hanchuanchuan/bingo2sql#10]
解析mariadb10.1.45的时候 用此./bingo2sql --host=x.x.x.x   -P 3306 --user=test --password=1234qwer -d jiexi    --start-time="2020-07-01 16:04:05" --stop-time="2020-07-06 16:11:05" -t students -B --debug                                 
INFO[2020-07-07T09:59:33+08:00] binlog信息                                      binlogFile=mysql-145bin.000001 file=parser.go line=915 起始时间="2020-07-01 13:48:48"
INFO[2020-07-07T09:59:33+08:00] 根据指定的时间段,解析出的开始binlog文件是:mysql-145bin.000001,结束文件是:mysql-145bin.000001  file=parser.go line=932
INFO[2020-07-07T09:59:33+08:00] create BinlogSyncer with config {2000000111  192.168.137.145 3306 test    false false <nil> false UTC true 0 0s 0s 0 false false 0}  file=binlogsyncer.go line=144
INFO[2020-07-07T09:59:33+08:00] begin to sync binlog from position (mysql-145bin.000001, 0)  file=binlogsyncer.go line=359
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000001, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000002, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000003, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000004, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000005, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000006, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000007, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000008, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000009, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000010, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000011, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000012, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] rotate to (mysql-145bin.000013, 4)            file=binlogsyncer.go line=776
INFO[2020-07-07T09:59:33+08:00] 已超出指定位置                                       file=parser.go line=502 当前位置=4 当前文件=mysql-145bin.000002 结束位置=0 结束文件=mysql-145bin.000001
WARN[2020-07-07T09:59:33+08:00] is finish                                     file=parser.go line=2143
INFO[2020-07-07T09:59:33+08:00] 解析完成                                          file=parser.go line=449
INFO[2020-07-07T09:59:33+08:00] syncer is closing...                          file=binlogsyncer.go line=175
INFO[2020-07-07T09:59:33+08:00] kill last connection id 145                   file=binlogsyncer.go line=849
INFO[2020-07-07T09:59:33+08:00] syncer is closed                              file=binlogsyncer.go line=202
什么也没有解析出来，但是./bingo2sql --host=192.168.137.145 -P 3306 --user=test --password=1234qwer -d jiexi  --start-file=mysql-145bin.000010   --start-time="2020-07-01 16:04:05" --stop-time="2020-07-06 16:11:05" -t students -B --debug 就可以解析出来了。为什么？看你的参数解释，没明白为啥？

**Comment by hanchuanchuan** [comment]
该问题已修复，之前判断结束文件逻辑有误，导致不指定起止文件时仅解析第一个binlog文件。

请选择 `v1.0.2-25` 及之后版本下载。

**Comment by guolong123** [comment]
> 该问题已修复，之前判断结束文件逻辑有误，导致不指定起止文件时仅解析第一个binlog文件。
> 
> 请选择 `v1.0.2-25` 及之后版本下载。

能打个包吗，我看最新的release包还是3月份的!

**Comment by guolong123** [comment]
> > 该问题已修复，之前判断结束文件逻辑有误，导致不指定起止文件时仅解析第一个binlog文件。
> > 请选择 `v1.0.2-25` 及之后版本下载。
> 
> 能打个包吗，我看最新的release包还是3月份的!

不好意思看错了。最新的release里面有1.0.2-25的版本。
