### ISSUE TITLE
ERRO  Get event error: context deadline exceeded    file=parser.go line=386 啥意思？

### ISSUE THREAD

**Issue by hope1234567hope** [hanchuanchuan/bingo2sql#12]
使用的是bingo2sql-linux-v1.0.2-25-g74b264a.tar.gz版本，数据库版本mariadb 10.1.48
[root@formysql8 opt]# ./bingo2sql --host=127.0.0.1 -P 3306 --user=root --password=1234qwer -d test --start-time="2020-07-01 16:04:05" --stop-time="2020-12-02 10:50:05" -t user -B --debug  
INFO[2020-12-02T11:09:02+08:00] binlog信息                                      binlogFile=mysql-bin138.000001 file=parser.go line=915 起始时间="2020-12-01 14:03:22"
INFO[2020-12-02T11:09:02+08:00] binlog信息                                      binlogFile=mysql-bin138.000002 file=parser.go line=915 起始时间="2020-12-01 14:50:46"
INFO[2020-12-02T11:09:02+08:00] binlog信息                                      binlogFile=mysql-bin138.000003 file=parser.go line=915 起始时间="2020-12-02 10:22:52"
INFO[2020-12-02T11:09:02+08:00] 根据指定的时间段,解析出的开始binlog文件是:mysql-bin138.000001,结束文件是:  file=parser.go line=931
INFO[2020-12-02T11:09:02+08:00] create BinlogSyncer with config {2000000111  127.0.0.1 3306 root    false false <nil> false UTC true 0 0s 0s 0 false false 0}  file=binlogsyncer.go line=144
INFO[2020-12-02T11:09:02+08:00] begin to sync binlog from position (mysql-bin138.000001, 0)  file=binlogsyncer.go line=359
INFO[2020-12-02T11:09:02+08:00] rotate to (mysql-bin138.000001, 4)            file=binlogsyncer.go line=776
INFO[2020-12-02T11:09:02+08:00] rotate to (mysql-bin138.000002, 4)            file=binlogsyncer.go line=776
INFO[2020-12-02T11:09:02+08:00] rotate to (mysql-bin138.000003, 4)            file=binlogsyncer.go line=776
INFO[2020-12-02T11:09:02+08:00] 超出最新binlog位置                                  file=parser.go line=502 当前位置=4588 当前文件=mysql-bin138.000003 结束位置=0 结束文件=
DELETE FROM `test`.`user` WHERE `id`=12; # 2020-12-02 10:49:26
DELETE FROM `test`.`user` WHERE `id`=13;
DELETE FROM `test`.`user` WHERE `id`=14;
DELETE FROM `test`.`user` WHERE `id`=15;
DELETE FROM `test`.`user` WHERE `id`=16;
DELETE FROM `test`.`user` WHERE `id`=17;
DELETE FROM `test`.`user` WHERE `id`=18;
DELETE FROM `test`.`user` WHERE `id`=19;
DELETE FROM `test`.`user` WHERE `id`=20;
DELETE FROM `test`.`user` WHERE `id`=21;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=12;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=13;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=14;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=15;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=16;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=17;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=18;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=19;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=20;
UPDATE `test`.`user` SET `end_time`=NULL WHERE `id`=21;
ERRO[2020-12-02T11:09:12+08:00] Get event error: context deadline exceeded    file=parser.go line=386
INFO[2020-12-02T11:09:12+08:00] 解析完成                                          file=parser.go line=449
INFO[2020-12-02T11:09:12+08:00] syncer is closing...                          file=binlogsyncer.go line=175
INFO[2020-12-02T11:09:12+08:00] kill last connection id 116                   file=binlogsyncer.go line=849
INFO[2020-12-02T11:09:12+08:00] syncer is closed                              file=binlogsyncer.go line=202
解析倒是出来了，但是有ERRO[2020-12-02T11:09:12+08:00] Get event error: context deadline exceeded    file=parser.go line=386 请问这个是啥原因？（其他的解析语句也会出现这个 Get event error: context deadline exceeded    file=parser.go的错误提示）

还有就是解析的sql中user表已经delete数据，后面的update已经没有意义了。

**Comment by hanchuanchuan** [comment]
出现错误`Get event error: context deadline exceeded`的原因是binlog在10s没有新事件产生, 此时会自动关闭解析,解析已完成.
该信息非错误,稍后我调整一下日志等级.

至于`DELETE`后面的`UPDATE`,这个挺奇怪的,binlog事件是这样子的,可以和`mysqlbinlog`解析的结果对比一下事件看是否一致.

**Comment by hanchuanchuan** [comment]
fixed.
现在可升级到 [v1.0.2-31](https://github.com/hanchuanchuan/bingo2sql/releases) 重试

**Comment by hope1234567hope** [comment]
谢谢作者的快速回复，支持你！

**Comment by hope1234567hope** [comment]
还有我是先insert数据，然后再update，其实生成undo的语句的时候，我觉得显示的时候应该倒叙显示下(先update再delete)，否则就像上面的已经delete了，再update已经没有意义了。个人意见

**Comment by hanchuanchuan** [comment]
不好意思我看错了,以为没有`--flashback`选项.

这个之所以没有倒序是因为解析结果是异步批量写入文件或者控制台的,不太方便再做一次倒序了,这样内存消耗比较大,性能也不好.
如果想要倒序的结果,在linux平台可以手动执行一次`tac`命令.单行SQL的执行时间放在了行末,就是为了这种情况的.

**Comment by hope1234567hope** [comment]
谢谢你的回复
又发现一个问题，是关于mariadb的，这次版本是10.3.14。
./bingo2sql --host=127.0.0.1 -P 3307 --user=root --password=qwer1234 -d uatdb --start-file=mariadb151_binlog.000016 --stop-file=mariadb151_binlog.000016 -t user
UPDATE `uatdb`.`user` SET `end_time`='2020-01-06 11:30:45' WHERE `id`=1; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2019-09-16 12:56:56' WHERE `id`=2;
UPDATE `uatdb`.`user` SET `end_time`='2020-01-15 12:41:27' WHERE `id`=3;
UPDATE `uatdb`.`user` SET `end_time`='2019-12-22 13:13:30' WHERE `id`=4;
UPDATE `uatdb`.`user` SET `end_time`='2020-02-21 13:54:33' WHERE `id`=5;
UPDATE `uatdb`.`user` SET `end_time`='2019-12-25 11:13:50' WHERE `id`=6;
UPDATE `uatdb`.`user` SET `end_time`='2019-12-26 13:54:26' WHERE `id`=7;
UPDATE `uatdb`.`user` SET `end_time`='2020-01-09 12:52:33' WHERE `id`=8;
UPDATE `uatdb`.`user` SET `end_time`='2020-02-13 15:12:38' WHERE `id`=9;
UPDATE `uatdb`.`user` SET `end_time`='2019-12-02 16:35:33' WHERE `id`=10;
但是mariadb151_binlog.000016中user表开始是insert，后update的，但是此解析中没有了insert的语句。(使用--start-time时间区间也会重现此现象)
使用./bingo2sql --host=127.0.0.1 -P 3307 --user=root --password=qwer1234 -d uatdb --start-file=mariadb151_binlog.000016  -t user  --ddl  可以看到insert和update的语句

**Comment by hanchuanchuan** [comment]
检查了`--ddl`选项没什么问题.
可以开启`--show-all-time`看一下执行的SQL时间.

**Comment by hope1234567hope** [comment]
你好：
MariaDB [(none)]> show binlog events in'mariadb151_binlog.000016' 可以看到如下(截取一部分)
| mariadb151_binlog.000016 |  995 | Query             |        31 |        1541 | use `uatdb`; CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_data_p`(IN num INT)
BEGIN
DECLARE n INT DEFAULT 1;
WHILE n <= num DO
INSERT INTO user( card, name, equipment_id, area_id, start_time)
VALUES( concat('A',n), concat('li',n), 0, 0, concat('2019-0',floor(8+rand()*5),'-0', floor(1+rand()*30),' ', floor(10+rand()*10),':',floor(10+rand()*49),':',floor(10+rand()*49)));
set n=n+1;
end while;
UPDATE user SET end_time=DATE_ADD(start_time, INTERVAL rand()*60 DAY);
END                                |
| mariadb151_binlog.000016 | 1541 | Gtid              |        31 |        1583 | BEGIN GTID 0-31-170                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| mariadb151_binlog.000016 | 1583 | Intvar            |        31 |        1615 | INSERT_ID=1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| mariadb151_binlog.000016 | 1615 | RAND              |        31 |        1654 | rand_seed1=292208766,rand_seed2=890920989                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| mariadb151_binlog.000016 | 1654 | Query             |        31 |        1999 | use `uatdb`; INSERT INTO user( card, name, equipment_id, area_id, start_time)
VALUES( concat('A', NAME_CONST('n',1)), concat('li', NAME_CONST('n',1)), 0, 0, concat('2019-0',floor(8+rand()*5),'-0', floor(1+rand()*30),' ', floor(10+rand()*10),':',floor(10+rand()*49),':',floor(10+rand()*49)))         
此时有insert的，后面还有update()
但是用
./bingo2sql --host=127.0.0.1 -P 3307 --user=root --password=qwer1234 -d uatdb --start-file=mariadb151_binlog.000016 --stop-file=mariadb151_binlog.000016 -t user  --debug --show-all-time
INFO[2020-12-07T10:23:59+08:00] create BinlogSyncer with config {2000000111  127.0.0.1 3307 root    false false <nil> false UTC true 0 0s 0s 0 false false 0}  file=binlogsyncer.go line=144
INFO[2020-12-07T10:23:59+08:00] begin to sync binlog from position (mariadb151_binlog.000016, 0)  file=binlogsyncer.go line=359
INFO[2020-12-07T10:23:59+08:00] rotate to (mariadb151_binlog.000016, 4)       file=binlogsyncer.go line=776
INFO[2020-12-07T10:23:59+08:00] rotate to (mariadb151_binlog.000017, 4)       file=binlogsyncer.go line=776
INFO[2020-12-07T10:23:59+08:00] rotate to (mariadb151_binlog.000017, 4)       file=binlogsyncer.go line=776
INFO[2020-12-07T10:23:59+08:00] rotate to (mariadb151_binlog.000018, 4)       file=binlogsyncer.go line=776
INFO[2020-12-07T10:23:59+08:00] 超出指定结束文件                                      file=parser.go line=512 当前位置=4 当前文件=mariadb151_binlog.000017 结束位置=0 结束文件=mariadb151_binlog.000016
WARN[2020-12-07T10:23:59+08:00] is finish                                     file=parser.go line=2175
UPDATE `uatdb`.`user` SET `end_time`='2020-01-06 11:30:45' WHERE `id`=1; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2019-09-16 12:56:56' WHERE `id`=2; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2020-01-15 12:41:27' WHERE `id`=3; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2019-12-22 13:13:30' WHERE `id`=4; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2020-02-21 13:54:33' WHERE `id`=5; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2019-12-25 11:13:50' WHERE `id`=6; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2019-12-26 13:54:26' WHERE `id`=7; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2020-01-09 12:52:33' WHERE `id`=8; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2020-02-13 15:12:38' WHERE `id`=9; # 2020-12-04 10:36:15
UPDATE `uatdb`.`user` SET `end_time`='2019-12-02 16:35:33' WHERE `id`=10; # 2020-12-04 10:36:15
INFO[2020-12-07T10:23:59+08:00] 解析完成                                          file=parser.go line=459 parsed_rows=10
INFO[2020-12-07T10:23:59+08:00] syncer is closing...                          file=binlogsyncer.go line=175
INFO[2020-12-07T10:23:59+08:00] kill last connection id 21                    file=binlogsyncer.go line=849
INFO[2020-12-07T10:23:59+08:00] syncer is closed                              file=binlogsyncer.go line=202
只看到了update的，没有前面insert的，以前数据库版本mariadb 10.1.48用这个语句是可以看到insert的。

**Comment by hanchuanchuan** [comment]
检查一下`binlog_format`.
```sql
show variables like 'binlog_format';
```

**Comment by hope1234567hope** [comment]
确实是，数据库版本不同的，binlog_format的默认值都变了，没有注意到。抱歉

**Comment by hanchuanchuan** [comment]
哈哈,还真是.我看到Insert那一行的`event_type`是`Query`,
而本地测试是 `Rows_query`,`Query`事件的内容应该是"BEGIN".

当前的`binlog_format`格式应该是混合模式吧, 所以才出现了INSERT和UPDATE的差异,一个语句,一个Row Event.
问题确认了就好,我之后加一个警告信息,提醒一下不是行模式的`binlog_format`.
