### ISSUE TITLE
解析的文件数据不全

### ISSUE THREAD

**Issue by wxtt522** [hanchuanchuan/bingo2sql#18]
使用同一个binlog文件做解析，缺失了几条insert和update语句，但单独指定--sql-type=insert 又能解析到对应的sql
![image](https://user-images.githubusercontent.com/28422636/187588214-672e1378-abc9-44c3-a6af-eb74dfdc6a4f.png)
![image](https://user-images.githubusercontent.com/28422636/187588381-1948ef80-b299-43df-b101-711b95b22a4d.png)

**Comment by hanchuanchuan** [comment]
其他的参数限制呢

**Comment by hanchuanchuan** [comment]
后面显示的行数吗, 如果是的话可以试试`--minimal-insert=false`, insert语句默认是合并的.
另外可尝试忽略设置--sql-type看一下结果.

**Comment by wxtt522** [comment]
不是的，我得出缺失的结论是我使用mysqlbinlog工具和bingo2sql恢复同一个binlog文件，针对单表发生的数据缺失。因为是生产数据不方便直接贴数据，后继测试有结论会回来补这个问题
