### ISSUE TITLE
测试空binlog显示数据

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/bingo2sql#2]
`./bingo2sql -h 192.168.60.152 -u ops -p 123456 -d sbtest -B --start-file='mysql-binlog.000002' --minimal-insert=false -o test.sql`
![image](https://user-images.githubusercontent.com/8868514/75625805-7c172800-5bfc-11ea-9930-2253ce626f42.png)

`mysqlbinlog /home/mysql/data/mysql-binlog.000002`
![image](https://user-images.githubusercontent.com/8868514/75625769-2f335180-5bfc-11ea-9137-21b9f00cf8ea.png)

` python binlog2sql/binlog2sql/binlog2sql.py -h 192.168.60.152 -u ops -p 123456 -d sbtest -B --start-file='mysql-binlog.000002' > test.sql`
![image](https://user-images.githubusercontent.com/8868514/75625791-60ac1d00-5bfc-11ea-9a94-5777a45b5abf.png)

![image](https://user-images.githubusercontent.com/8868514/75625858-ffd11480-5bfc-11ea-80f4-2975ed06df2e.png)

**Comment by hanchuanchuan** [comment]
看一下 ```show master status;``` 如果没有指定结束位置的话，会持续解析到最新位置的，而不仅是一个binlog文件。

**Comment by liuqian1990** [comment]
![image](https://user-images.githubusercontent.com/8868514/75625986-5854e180-5bfe-11ea-9ec5-212b1fe5991a.png)

如果持续解释那应该有几百W数据

**Comment by hanchuanchuan** [comment]
```--max```参数的默认解析上限是10w行。
