### ISSUE TITLE
[BUG] NULL值未处理导致进程崩溃

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/bingo2sql#4]
panic: interface conversion: interface {} is nil, not []uint8

goroutine 1 [running]:
github.com/hanchuanchuan/bingo2sql.compareValue(0xcf5220, 0xc00054ae80, 0x0, 0x0, 0x1)
	/root/hcc/bingo2sql/parser.go:2058 +0x1a5
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).generateUpdateSQL(0xc000237900, 0xc0011b8640, 0xc0005accc0, 0xc0005af500, 0xc00036412a, 0xc000100301)
	/root/hcc/bingo2sql/parser.go:1347 +0xf21
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).parseSingleEvent(0xc000237900, 0xc0005af500, 0xc00120d860, 0xc0005af500, 0x0)
	/root/hcc/bingo2sql/parser.go:2237 +0xa29
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).Parser(0xc000237900, 0x0, 0x0)
	/root/hcc/bingo2sql/parser.go:390 +0x4e0
main.runParse()
	/root/hcc/bingo2sql/cmd/bingo2sql.go:185 +0x3dd
main.main()
	/root/hcc/bingo2sql/cmd/bingo2sql.go:128 +0x199

**Comment by hanchuanchuan** [comment]
问题已修复, 可下载最新的release文件 [fix: 修复部分类型null值未处理的bug](https://github.com/hanchuanchuan/bingo2sql/commit/526aae69c2e56fdc00958112384c89102fad0f66)

**Comment by liuqian1990** [comment]
这个怎么看出来是空值问题

**Comment by hanchuanchuan** [comment]
报错可以看出来一部分 ` interface {} is nil, not []uint8 ` ，
之后看代码以及添加测试用例做确认和修复即可。
