### ISSUE TITLE
driver: skip fast-path; continue as if unimplemented 

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/bingo2sql#5]
ERRO[2020-03-19T17:27:36+08:00] driver: skip fast-path; continue as if unimplemented  file=parser.go line=1043
ERRO[2020-03-19T17:27:37+08:00] close sync with err: sync is been closing...  file=binlogstreamer.go line=77
panic: driver: skip fast-path; continue as if unimplemented

goroutine 1 [running]:
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).checkError(0xc000241900, 0xfa8580, 0xc004c22680)
	/Users/hanchuanchuan/hcc/bingo2sql/parser.go:1050 +0x24d
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).generateUpdateSQL(0xc000241900, 0xc000128000, 0xc019eea000, 0xc0190202a0, 0xc00035412a, 0xc019ecc001)
	/Users/hanchuanchuan/hcc/bingo2sql/parser.go:1373 +0x117c
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).parseSingleEvent(0xc000241900, 0xc0190202a0, 0xc019ece240, 0xc0190202a0, 0x0)
	/Users/hanchuanchuan/hcc/bingo2sql/parser.go:2246 +0xa14
github.com/hanchuanchuan/bingo2sql.(*MyBinlogParser).Parser(0xc000241900, 0x0, 0x0)
	/Users/hanchuanchuan/hcc/bingo2sql/parser.go:390 +0x543
main.runParse()
	/Users/hanchuanchuan/hcc/bingo2sql/cmd/bingo2sql.go:185 +0x3d5
main.main()
	/Users/hanchuanchuan/hcc/bingo2sql/cmd/bingo2sql.go:128 +0x1c3

**Comment by hanchuanchuan** [comment]
帮忙确认一下还有没有更多日志，在该日志之前还有一些信息

**Comment by liuqian1990** [comment]
没有了，这是全部的了

**Comment by hanchuanchuan** [comment]
单行超过4MB了吗？
如果不是的话，麻烦开启 `debug` 参数重试一下

**Comment by liuqian1990** [comment]
是的

**Comment by liuqian1990** [comment]
超过了

**Comment by hanchuanchuan** [comment]
问题已修复 [release v1.0.2](https://github.com/hanchuanchuan/bingo2sql/releases/tag/v1.0.2)
